Remove plone.app.registry fixture from test setup. This fixture adds a second PLONE_FIXTURE into the test setup which leads to 'AttributeError: 'NoneType' object has no attribute 'load''. This also leads to the test fixture to bleeding into the unit tests (e.g. test_query.py) which makes them 'magically' pass.